### ISSUE TITLE
Preload fonts before showing next pun

### ISSUE THREAD

**Issue by maricn** [AlexLakatos/computer-puns#25]
When going through puns, they are momentarily displayed in one font for a blink of an eye, and then their actual display font is loaded and they're re-rendered.

**Comment by brunomguimaraes** [comment]
Yeah, I was going to come here for the exact same reason.
Is there any way @AlexLakatos can make an open repo for client-side so we can contribute?

**Comment by AlexLakatos** [comment]
It's this repo, it's all open. The site gets generated from the `gh-pages` branch of this repo, so feel free to open a PR for the fonts issue!

**Comment by AlexLakatos** [comment]
Fixed!
